Repository seL4/ci-actions, pull requests merged in 2022-02, with the labels that each got.

#183 standalone-kernel: support AARCH64 config
  standalone-kernel/README.md
  standalone-kernel/action.yml
  standalone-kernel/compile_kernel.sh
Labels: seL4

#191 pass through PA tokens for private repo access
  bashisms/README.md
  bashisms/action.yml
  git-diff-check/README.md
  git-diff-check/action.yml
  gitlint/README.md
  gitlint/action.yml
  style/README.md
  style/action.yml
  thylint/README.md
  thylint/action.yml
Labels: enhancement

#192 doc: fix description
  repo-checkout/action.yml
Labels: documentation

#195 thylint: missing files are not an error in diff-only mode
  thylint/thylint.py
Labels: verification
