Repository seL4/ci-actions, pull requests merged in 2024-01, with the labels that each got.

#296 fix typos
  sel4test-sim/README.md
  sel4test-sim/action.yml
Labels: documentation

#297 support LLVM for RISCV64 kernel stand alone build
  standalone-kernel/compile_kernel.sh
Labels: seL4

#301 sel4test-hw: remove mcs+hyp+smp+clang for TX1
  sel4test-hw/build.py
Labels: seL4

#307 sel4test-hw: skip riscv+clang+smp+release
  sel4test-hw/build.py
Labels: seL4

#308 platforms: haswell4 is available again
  seL4-platforms/platforms.yml
Labels: boards

#309 platforms: disable MCS for Maaxboard for now
  seL4-platforms/platforms.yml
Labels: seL4

#315 bashisms: bump devscripts version
  bashisms/README.md
Labels: dependencies

#314 camkes-vm: add vm_minimal_zcu102 run
  camkes-vm/build.py
  camkes-vm/builds.yml
Labels: camkes

#316 camkes-vm: fix typo in settings key string
  camkes-vm/builds.yml
Labels: bug

#317 camkes-vm: add vm_minimal for ODROID_C2
  camkes-vm/builds.yml
Labels: boards

#319 camkes-vm: test ping/arping on zcu102
  camkes-vm/builds.yml
Labels: camkes, boards
